### ISSUE TITLE
Cannot connect to ImmuneSpace with current netrc information -- check login and password for errors with STATUS 404

### ISSUE THREAD

**Issue by fishmatt** [RGLab/ImmuneSpaceR#122]
Hi, 
Running through a piece of analysis that I can no longer get to. The issue seemed similar to [https://github.com/RGLab/ImmuneSpaceR/issues/99]

I try to connect to the immune space server using the correct log in information that works on the website. 
`interactive_netrc()`
and get the output 

> Validating netrc ...
Cannot connect to ImmuneSpace with current netrc information -- check login and password for errors

I went through the comments and noticed that when I run, as suggested in Issue 99.
`httr::GET("https://www.immunespace.org/login-whoami.view", Rlabkey:::labkey.getRequestOptions())`

I get this output which includes status 404. (Different to 200 in issue 99)

> Response [https://immunespace.org/login-whoami.view]
>   Date: 2023-11-15 16:11
>   Status: 404
>   Content-Type: text/html; charset=utf-8
>   Size: 3.02 kB
> 
> 
> 
> 
> <!doctype html>
> <html prefix="og: http://ogp.me/ns#" lang="en-us">
> 
> <head>
>   
>   
> ...

I have tried:
Changing machines.
clearing and restarting the R environment (attempting to remove any labkey.url.base variable defined)
Writing my own .netrc file in command line. 

Your advice is much appreciated! 
Best 
Matt

**Comment by jgbaum** [comment]
Hi @fishmatt ,

Thanks for reporting this.  As noted [here](https://github.com/RGLab/ImmuneSpaceR), the URL in your .netrc file needs to be updated to point to ```datatools.immunespace.org```.  Unfortunately, that seems to be only part of the issue.  I'm working to track down the remaining bits and will update this ticket once we figure it out.

Thanks for your patience.

**Comment by jgbaum** [comment]
Hi @fishmatt,

It seems this issue is caused by a recent update to the Rlabkey package.  In version 3.0.0 (released 11/7/2023), a change was made to the labkey.executeSql function that caused an incompatibility with our systems:

https://cran.r-project.org/web/packages/Rlabkey/NEWS

We are in the process of evaluating how to resolve this issue.  In the meantime, downgrading to an earlier version of Rlabkey (e.g., 2.12.0) resolves the issue.

**Comment by fishmatt** [comment]
Hi, Thanks for solving this. I can confirm the .Netrc file was updated to` datatools.immunespace.org`. 

I have also installed the Rlabkey package 2.12.0. Restarted R, loaded the Rlabkey package followed by immune space and have now god access. Thanks so much for your help! 
Good luck with resolving it for the latest one.
