### ISSUE TITLE
Error in function (type, msg, asError = TRUE)  : 

### ISSUE THREAD

**Issue by dfermin** [RGLab/ImmuneSpaceR#2]
Hi.

I'm trying to follow the vignette on how to use ImmuneSpaceR.
I've managed to install the packages (ImmuneSpaceR + Rlabkey).

When I try to create a connection I get this error:
> sdy269 <- CreateConnection(study="SDY269", verbose=TRUE)
Error in function (type, msg, asError = TRUE)  : 
  Unknown cipher in list: ALL

I am following the vignette example to start with.
I've created a $HOME/.netrc file with my credentials for logging into ImmuneSpace.
I'm running "R version 3.1.1 (2014-07-10)"
On Fedora 20 (fully patched).

Any and all help would be greatly appreciated.
Thanks,
Damian

This is my code:
######################################################
library(ImmuneSpaceR)

labkey.url.base="https://www.immunespace.org"
labkey.url.path="Studies/SDY269"
labkey.email.user="damian.fermin at yale.edu"

sdy269 <- CreateConnection(study="SDY269", verbose=TRUE)
#######################################################

**Comment by raphg** [comment]
I think this has been resolved.
