### ISSUE TITLE
Unable to CreateConnection: invalid credentials, but login/password work via web portal

### ISSUE THREAD

**Issue by cashoes** [RGLab/ImmuneSpaceR#99]
Re-running through a bit of analysis that *used* to work. I get an error when trying to create a connection.

> Error in .CreateConnection(study = study, labkey.url.base = labkey.url.base,  : 
  Invalid credential or deactivated account. Check your account in the portal.

Credentials appear to be valid when accessing ImmuneSpace via the web portal. This is using R 3.5 running on a Windows machine.

Steps taken:
- Reset my password on the portal and tried again after restarting my R instance and updating my _netrc file.
- That's pretty much it...

**Comment by juyeongkim** [comment]
What's the version of `ImmuneSpaceR` you are using?

```R
packageVersion("ImmuneSpaceR")
```

**Comment by cashoes** [comment]
Version: 1.11.2

**Comment by juyeongkim** [comment]
Try installing the latest development version of `ImmuneSpaceR`:

```R
remotes::install_github("RGLab/ImmuneSpaceR")
```

And update your netrc file via:

```R
ImmuneSpaceR::interactive_netrc()
```

Your netrc should be located at:

```
"C:/Users/yourUsername/Documents/_netrc"
```

And it should look something like this:

```
machine www.immunespace.org
login  you@yourSite.org
password  yourPassword
```

**Comment by cashoes** [comment]
Thanks - updated to 1.11.7, but I still get the same problem.

I don't know if this will help, but running:
`
ImmuneSpaceR::check_netrc()
`

Fails with:
`
Error in ImmuneSpaceR::check_netrc() : There is no netrc file. Use `write_netrc`
`
Apparently because the check for a '.netrc' in the home folder is hardcoded (not platform dependent). Is this function called internally by `CreateConnection()` at all?

**Comment by juyeongkim** [comment]
Gotcha. Yeah that's a bug. It shouldn't be hardcoded like that. Thanks! We will fix that. But no it's not called internally by `CreateConnection()`.

I am thinking something is wrong in netrc file. How did you create your netrc file? Have you tried `interactive_netrc()`?

The alternative way to create a connection is to pass your credentials in `CreateConnection()` call:

```R
con <- CreateConnection("", login = "you@yourSite.org", password = "yourSecretPassword")

**Comment by cashoes** [comment]
Yes, I did try `interactive_netrc()`, the information within is correct (as in, it is the same as the email and password that allow me to log in through the web portal). Overwriting and rewriting the same information (or selecting no and doing nothing) results in:

`
Validating netrc ...
Cannot connect to ImmuneSpace with current netrc information -- check login and password for errors
`

I also tried directly passing my username (I used email address?) and password to `CreateConnection` and still get invalid credentials, so I'm totally stumped at this point. Seems my credentials aren't valid... but the web portal seems ok with them.

**Comment by juyeongkim** [comment]
That is really weird. I'm really sorry about this.

Could you try this and share the output?

```R
httr::GET("https://www.immunespace.org/login-whoami.view", Rlabkey:::labkey.getRequestOptions())
```

**Comment by cashoes** [comment]
`
Response [https://www.immunespace.org/login-whoami.view]
  Date: 2019-05-06 22:50
  Status: 200
  Content-Type: application/json;charset=UTF-8
  Size: 151 B
{
  "displayName" : "casey",
  "success" : true,
  "id" : 1456,
  "CSRF" : "d5966653f57cd8b39ad3b0307ceb339a",
  "email" : "casey.shannon@hli.ubc.ca"
`

**Comment by juyeongkim** [comment]
Hmmmm strange. Your netrc file seems to be valid, and `CreateConnection` shouldn't be giving the invalid credential error since that response is neither 401 status or returning as guest. https://github.com/RGLab/ImmuneSpaceR/blob/master/R/ISCon.R#L496

I just checked your account permissions, and they are good. I am running out of ideas at this point.

- Do you have `labkey.url.base` variable defined in global environment by any chance? If so, remove it and try again.
- Update `Rlabkey`, `httr`, and `curl` packages to the latest version and try again.
- Sometimes `curl` doesn't pick up the updated netrc file. Restart your R session and try again in fresh R session.

I apologize for the inconvenience and thank you for your patience.

**Comment by cashoes** [comment]
Thanks for your patience... `labkey.url.base` was the guilty party. Since RStudio restores the last project on open, the variable was globally defined everytime I restarted.

I was using an .Rmd that Evan Henrich shared with me a few weeks ago which included setting up `labkey.url.base' globally to access the test server... I guess that's not something I have access to with my personal credentials.

Thanks for all your help with this.

**Comment by juyeongkim** [comment]
Gotcha. I am glad I was able to help. Let me know if you run into more issues with ImmuneSpace or ImmuneSpaceR or have any suggestions. Thank you!
